#!/bin/bash

function usage {
	cat << EOF
SET_ENV
=======

Set the environment in order to use the application.

This script will add the set of tool to the path. All utility will be
available directly from the command line after being executed.


Usage
-----

source load_env
EOF
}


while getopts "h" arg; do
  case $arg in
		h)
			usage
			exit 0
			;;
	esac
done

DIR=$(readlink --canonicalize $(dirname exchange.sh))
PATH="$PATH:$DIR/bin"


